### ISSUE TITLE
Old version of openssl used in droidphph which is vulnarable to heartbleed

### ISSUE THREAD

**Issue by jeetbhatnagar** [DroidPHP/DroidPHP#60]
I have tried to compile lighttpd and php with latest version of openssl using compllie.md doc for removing this bug but was not able to compile successfully,can this be included in the next release of droidphpor if someone can provide compiled version of droidphp with latest version of openssl.

**Comment by Zaxscdvf** [comment]
ya this needs to be fixed Immediately.

**Comment by shushant** [comment]
Thanks for informing but i cant provide intimidate fix due i am not getting enough time for this project because i am busy in preparing for engineering entrance exam.

**Comment by Zaxscdvf** [comment]
@shushant i understand but when do you think you will able to have more time on this project?

**Comment by jeetbhatnagar** [comment]
@sushant any update on this,this is an urgent requirement

**Comment by Zaxscdvf** [comment]
ya this project should be put on hold in till the developer can fixe multiple issues.

**Comment by shushant** [comment]
Yes i have update the openssl to 1.0.1f soory for delay i was working on new build system based on symfony's console component to automate the cross compile.
Update is available via Package Manager and click on `Components Security Fix` to update it.

**Comment by jeetbhatnagar** [comment]
thanks Sushant even we were able to successfully compile droidphp but problem after compiling that we are facing is that we are not able to execute exec() command while in older version of droidphp we were able to do so.On comparing configuration option in older version and the configuration option in the cross compiling document there was a lot of difference can you check if any configuration option  has disabled exec() and working of other such commands
