### ISSUE TITLE
How can i recover the deleted rows from table in MySql database ?

### ISSUE THREAD

**Issue by sourabhbans007** [DroidPHP/DroidPHP#61]
Hi , I have deleted some records from MySql table accidentally.And i have not backed up so my query is that how can retrieve that deleted rows.Please help me its urjent.

**Comment by Zaxscdvf** [comment]
https://stackoverflow.com/questions/6924823/how-to-recover-just-deleted-rows-in-mysql

**Comment by Zaxscdvf** [comment]
should have made a backup

**Comment by xinjijia** [comment]
www.dbfixserver.com support undrop table recovery and undelete rows recovery by innodb or myisam
