### ISSUE TITLE
localhost:8080 downloading exe file ?

### ISSUE THREAD

**Issue by gamecompiler** [DroidPHP/DroidPHP#64]
Hi, Id installed Droidphp today.
My PHP files are inside the htdocs folder like it should. If i press Web Admin i will be redirected to localhost:8080.

Why my system downloads exe files if i enter the Server through a Webbrowser ?

These files got crazy namens like:
i4urEbbP.exe
+PyGXl4d.exe

Please help Oo
Thanks in Advance.

**Comment by shushant** [comment]
Can you be more specific what program are you running?

**Comment by sartyx** [comment]
Same issue here, it isn´t an exe file just the wrong doctype:
Once installed all data comes by application/octet-stream (1,4 KB) with a random name.
