### ISSUE TITLE
error 404 where view web

### ISSUE THREAD

**Issue by guimax** [DroidPHP/DroidPHP#65]
hello, i installed droidphp in me smartphone, but not run. ocurre  error 404. have one file index.php in htdocs, not found web page however. please any idea?

**Comment by shushant** [comment]
From https://github.com/DroidPHP/DroidPHP/wiki/Getting_Started upload you code to directory `/mnt/sdcard/htdocs`

**Comment by guimax** [comment]
solved thank, my problem was i use folder htdocs into droidphp, the solution was create new folder in root sdcart with name htdocs, inside it copy index.php.

thank shushant!!!
