### ISSUE TITLE
How do i compile this with A.I.D.E?

### ISSUE THREAD

**Issue by develperbayman** [DroidPHP/DroidPHP#80]
Any help would be appriciated if someone could walk me thru getting this to compile on aide

**Comment by IriaSomobu** [comment]
First, download (or git clone) sources of this project. Try to comile it. You may have many errors (three hundred or so). Next steps will help you.

You need to download all dependences as jars or sources (google can help):
1. libsuperuser
2. SwipeCompatLibrary
3. actionbarsherlock
4. volley

Then add it to project in AIDE by long press on jar/project folder -> add library to project.

Finally, you need to compile project. If you still have errors - try to solve it manually or write here.

**Comment by develperbayman** [comment]
Thanks!!!!!!

**Comment by IriaSomobu** [comment]
You are welcome.

**Comment by vancentvan** [comment]
@iillyyaa2033 I have an issue described below...
I have just imported projects ActionBarShelock, libsuperuser and SwitchCompatLibrary, copied and pasted commons-lite-1.14.jar and volley.jar to folder libs for the full project. No error was shown in Eclipse. But when I built and run the full project, error "Could not find DroidPHP.apk!" emerged. 
I am wondering if you can give me some tips on that. Thanks a lot in advance...

**Comment by Duna** [comment]
#93

**Comment by develperbayman** [comment]
Sorry this was open for 4 years thanks again!!!!
